// Generated by scripts/generate_api_types.py. Do not edit.

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant' | 'tool'
  content: string
}

export interface Conversation {
  id: string
  title: string
  created_at: string
  updated_at: string
  messages?: Array<Message>
}

export interface ConversationCreate {
  title?: string
}

export interface CredentialInput {
  api_key: string
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>
}

export interface Message {
  role: 'system' | 'user' | 'assistant' | 'tool'
  content: string
  id: string
  position: number
  created_at: string
}

export interface MessageCreate {
  role: 'system' | 'user' | 'assistant' | 'tool'
  content: string
}

export interface OAuthCodeInput {
  code: string
}

export interface RunCreate {
  provider: string
  model: string
  messages: Array<ChatMessage>
  temperature?: number
  conversation_id?: string | null
}

export interface RunSnapshot {
  id: string
  status: RunStatus
  provider: string
  model: string
  output?: string
  error?: string | null
  created_at: string
  started_at?: string | null
  completed_at?: string | null
}

export type RunStatus = 'queued' | 'running' | 'completed' | 'cancelled' | 'failed'

export interface ValidationError {
  loc: Array<string | number>
  msg: string
  type: string
  input?: unknown
  ctx?: Record<string, unknown>
}
