"""Generate TypeScript component types from the FastAPI OpenAPI schema."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from backend.app.main import create_app


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "frontend" / "src" / "api" / "schema.ts"


def ts_type(schema: dict[str, Any]) -> str:
    if ref := schema.get("$ref"):
        return ref.rsplit("/", 1)[-1]
    if values := schema.get("enum"):
        return " | ".join(repr(value) for value in values)
    if variants := schema.get("anyOf"):
        return " | ".join(ts_type(variant) for variant in variants)
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object":
        return f"Record<string, {ts_type(schema.get('additionalProperties', {}))}>"
    return {"integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(
        kind, "string" if kind == "string" else "unknown"
    )


def render() -> str:
    schemas = create_app(database_url=":memory:").openapi()["components"]["schemas"]
    lines = ["// Generated by scripts/generate_api_types.py. Do not edit.\n"]
    for name, schema in sorted(schemas.items()):
        if values := schema.get("enum"):
            lines.append(f"export type {name} = {' | '.join(repr(value) for value in values)}\n")
            continue
        required = set(schema.get("required", []))
        lines.append(f"export interface {name} {{")
        for prop, details in schema.get("properties", {}).items():
            optional = "" if prop in required else "?"
            lines.append(f"  {prop}{optional}: {ts_type(details)}")
        lines.append("}\n")
    return "\n".join(lines)


if __name__ == "__main__":
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    print(OUTPUT.relative_to(ROOT))
